### ISSUE TITLE
[ISSUE]: Research GitHub API

### ISSUE THREAD

**Issue by ihagedo** [PurdueSoftEng/CLI-Tool#12]
### Type of Issue

Research

### Description of Issue

```shell
Research how to use the API, what are possible artifacts of the API, what are constraints of the API, will it be easy to plug into RUST or should we use another language.
```

### Is this a stalled or critical issue?

- [ ] Critical
- [ ] Stalled

**Comment by ihagedo** [comment]
We should make a bash script or equivalent that utilizes the GitHub API and extracts some information to an output file as a deliverable.

**Comment by GabbyWhitis** [comment]
attempting to close issue
