### ISSUE TITLE
[ISSUE]: Research GraphQL API

### ISSUE THREAD

**Issue by ihagedo** [PurdueSoftEng/CLI-Tool#13]
### Type of Issue

Research

### Description of Issue

```shell
Research how to use the API, what are possible artifacts of the API, what are constraints of the API, will it be easy to plug into RUST or should we use another language.
```

### Is this a stalled or critical issue?

- [ ] Critical
- [ ] Stalled

**Comment by emisenhe** [comment]
Research done so far:
Research Link: https://codeql.github.com/docs/codeql-cli/
CodeQL API: "The CodeQL command-line interface (CLI) is used to create databases for security research."
1. Research how to use the API
- CodeQL CLI Command to Run: codeql [command] [subcommand]
- How to set up the CodeQL CLI
  1.) Download the CodeQL CLI zip package 
  2.) Extract and Launch codeql 
  3.) There are commands to verify the CodeQL CLI setup 
- We can output the analysis results generated in CSV format (database analyze --format csv)
2. What are possible artifacts of the API?
- Can find vulnerabilities and errors in code that's written in the supported languages.
3. What are constraints of the API?
- Will not go through the RUST lines that are written. 
4. Will it be easy to plug into RUST or should we use another language.
- RUST was not listed as a supported language and framework on the CodeQL documentation
- These are the possible language guides:
  CodeQL for C and C++
  CodeQL for C#
  CodeQL for Go
  CodeQL for Java and Kotlin
  CodeQL for JavaScript
  CodeQL for Python
  CodeQL for Ruby
- Possible uses for Python compatability
  - Analyzing data flow in Python (local and global data flow -> isSource (used to get info))

**Comment by ihagedo** [comment]
We should make a bash script or equivalent that utilizes the CodeQL API and extracts some information to an output file as a deliverable.

**Comment by ihagedo** [comment]
https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/

**Comment by emisenhe** [comment]
Found this possible resource to create a GraphQL Server in Rust: https://blog.logrocket.com/how-to-create-a-graphql-server-in-rust/

**Comment by emisenhe** [comment]
I think we can use this for the basic bash script -- need more info before implementation though 
https://www.meetup.com/api/guide/#p02-querying-section
