### ISSUE TITLE
[ISSUE]: Develop argument handling for the CLI input

### ISSUE THREAD

**Issue by GabbyWhitis** [PurdueSoftEng/CLI-Tool#16]
### Type of Issue

Build

### Description of Issue

```shell
Using enums, add input type, output type, and source choice (GitHub vs npm). The main function will handle argument arbitration.
```

### Is this a stalled or critical issue?

- [ ] Critical
- [ ] Stalled

**Comment by ihagedo** [comment]
Change argument parsing to be handled by a c file which invokes three different bash scripts which handle our three input cases.
